#############################################################################
# Makefile for building: jetsonCamApp
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  build.pro
# Template: app
# Command: /home/dai/anaconda3/bin/qmake -o Makefile build.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/cuda/include -I/opt/spinnaker/include -I../../../anaconda3/include/qt -I../../../anaconda3/include/qt/QtCharts -I../../../anaconda3/include/qt/QtWidgets -I../../../anaconda3/include/qt/QtGui -I../../../anaconda3/include/qt/QtConcurrent -I../../../anaconda3/include/qt/QtCore -Imoc -I../../../anaconda3/include -I/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include -I/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include/libdrm -I/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include -I../../../anaconda3/mkspecs/linux-g++
QMAKE         = /home/dai/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/dai/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/dai/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = jetsonCamApp1.0.0
DISTDIR = /home/dai/Documents/repos/JetsonCamApp/obj/jetsonCamApp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/dai/anaconda3/lib
LIBS          = $(SUBLIBS) -L/opt/spinnaker/lib -lSpinnaker -L./obj -lcuda_functions -L/usr/local/cuda/lib64 -lcudart /home/dai/anaconda3/lib/libQt5Charts.so /home/dai/anaconda3/lib/libQt5Widgets.so /home/dai/anaconda3/lib/libQt5Gui.so /home/dai/anaconda3/lib/libQt5Concurrent.so /home/dai/anaconda3/lib/libQt5Core.so -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp moc/moc_appwindow.cpp
OBJECTS       = obj/main.o \
		obj/moc_appwindow.o
DIST          = ../../../anaconda3/mkspecs/features/spec_pre.prf \
		../../../anaconda3/mkspecs/common/unix.conf \
		../../../anaconda3/mkspecs/common/linux.conf \
		../../../anaconda3/mkspecs/common/sanitize.conf \
		../../../anaconda3/mkspecs/common/gcc-base.conf \
		../../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../../anaconda3/mkspecs/common/g++-base.conf \
		../../../anaconda3/mkspecs/common/g++-unix.conf \
		../../../anaconda3/mkspecs/qconfig.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdf.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda3/mkspecs/features/qt_functions.prf \
		../../../anaconda3/mkspecs/features/qt_config.prf \
		../../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../../anaconda3/mkspecs/features/spec_post.prf \
		../../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../../anaconda3/mkspecs/features/toolchain.prf \
		../../../anaconda3/mkspecs/features/default_pre.prf \
		../../../anaconda3/mkspecs/features/resolve_config.prf \
		../../../anaconda3/mkspecs/features/default_post.prf \
		../../../anaconda3/mkspecs/features/warn_on.prf \
		../../../anaconda3/mkspecs/features/qt.prf \
		../../../anaconda3/mkspecs/features/resources_functions.prf \
		../../../anaconda3/mkspecs/features/resources.prf \
		../../../anaconda3/mkspecs/features/moc.prf \
		../../../anaconda3/mkspecs/features/unix/opengl.prf \
		../../../anaconda3/mkspecs/features/uic.prf \
		../../../anaconda3/mkspecs/features/unix/thread.prf \
		../../../anaconda3/mkspecs/features/qmake_use.prf \
		../../../anaconda3/mkspecs/features/file_copies.prf \
		../../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../../anaconda3/mkspecs/features/exceptions.prf \
		../../../anaconda3/mkspecs/features/yacc.prf \
		../../../anaconda3/mkspecs/features/lex.prf \
		build.pro src/appwindow.h \
		src/camerahandler.h src/main.cpp
QMAKE_TARGET  = jetsonCamApp
DESTDIR       = 
TARGET        = jetsonCamApp


first: all
####### Build rules

jetsonCamApp:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: build.pro ../../../anaconda3/mkspecs/linux-g++/qmake.conf ../../../anaconda3/mkspecs/features/spec_pre.prf \
		../../../anaconda3/mkspecs/common/unix.conf \
		../../../anaconda3/mkspecs/common/linux.conf \
		../../../anaconda3/mkspecs/common/sanitize.conf \
		../../../anaconda3/mkspecs/common/gcc-base.conf \
		../../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../../anaconda3/mkspecs/common/g++-base.conf \
		../../../anaconda3/mkspecs/common/g++-unix.conf \
		../../../anaconda3/mkspecs/qconfig.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdf.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda3/mkspecs/features/qt_functions.prf \
		../../../anaconda3/mkspecs/features/qt_config.prf \
		../../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../../anaconda3/mkspecs/features/spec_post.prf \
		../../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../../anaconda3/mkspecs/features/toolchain.prf \
		../../../anaconda3/mkspecs/features/default_pre.prf \
		../../../anaconda3/mkspecs/features/resolve_config.prf \
		../../../anaconda3/mkspecs/features/default_post.prf \
		../../../anaconda3/mkspecs/features/warn_on.prf \
		../../../anaconda3/mkspecs/features/qt.prf \
		../../../anaconda3/mkspecs/features/resources_functions.prf \
		../../../anaconda3/mkspecs/features/resources.prf \
		../../../anaconda3/mkspecs/features/moc.prf \
		../../../anaconda3/mkspecs/features/unix/opengl.prf \
		../../../anaconda3/mkspecs/features/uic.prf \
		../../../anaconda3/mkspecs/features/unix/thread.prf \
		../../../anaconda3/mkspecs/features/qmake_use.prf \
		../../../anaconda3/mkspecs/features/file_copies.prf \
		../../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../../anaconda3/mkspecs/features/exceptions.prf \
		../../../anaconda3/mkspecs/features/yacc.prf \
		../../../anaconda3/mkspecs/features/lex.prf \
		build.pro
	$(QMAKE) -o Makefile build.pro
../../../anaconda3/mkspecs/features/spec_pre.prf:
../../../anaconda3/mkspecs/common/unix.conf:
../../../anaconda3/mkspecs/common/linux.conf:
../../../anaconda3/mkspecs/common/sanitize.conf:
../../../anaconda3/mkspecs/common/gcc-base.conf:
../../../anaconda3/mkspecs/common/gcc-base-unix.conf:
../../../anaconda3/mkspecs/common/g++-base.conf:
../../../anaconda3/mkspecs/common/g++-unix.conf:
../../../anaconda3/mkspecs/qconfig.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_charts.pri:
../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_core.pri:
../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designer.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gui.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_help.pri:
../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_location.pri:
../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_network.pri:
../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_pdf.pri:
../../../anaconda3/mkspecs/modules/qt_lib_pdf_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioningquick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3d.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3drender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_script.pri:
../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sql.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_svg.pri:
../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webview.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../anaconda3/mkspecs/features/qt_functions.prf:
../../../anaconda3/mkspecs/features/qt_config.prf:
../../../anaconda3/mkspecs/linux-g++/qmake.conf:
../../../anaconda3/mkspecs/features/spec_post.prf:
../../../anaconda3/mkspecs/features/exclusive_builds.prf:
../../../anaconda3/mkspecs/features/toolchain.prf:
../../../anaconda3/mkspecs/features/default_pre.prf:
../../../anaconda3/mkspecs/features/resolve_config.prf:
../../../anaconda3/mkspecs/features/default_post.prf:
../../../anaconda3/mkspecs/features/warn_on.prf:
../../../anaconda3/mkspecs/features/qt.prf:
../../../anaconda3/mkspecs/features/resources_functions.prf:
../../../anaconda3/mkspecs/features/resources.prf:
../../../anaconda3/mkspecs/features/moc.prf:
../../../anaconda3/mkspecs/features/unix/opengl.prf:
../../../anaconda3/mkspecs/features/uic.prf:
../../../anaconda3/mkspecs/features/unix/thread.prf:
../../../anaconda3/mkspecs/features/qmake_use.prf:
../../../anaconda3/mkspecs/features/file_copies.prf:
../../../anaconda3/mkspecs/features/testcase_targets.prf:
../../../anaconda3/mkspecs/features/exceptions.prf:
../../../anaconda3/mkspecs/features/yacc.prf:
../../../anaconda3/mkspecs/features/lex.prf:
build.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile build.pro

qmake_all: FORCE


all: Makefile jetsonCamApp

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/appwindow.h src/camerahandler.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: ../../../anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc/moc_predefs.h ../../../anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_appwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_appwindow.cpp
moc/moc_appwindow.cpp: src/appwindow.h \
		src/camerahandler.h \
		/opt/spinnaker/include/Spinnaker.h \
		/opt/spinnaker/include/SpinnakerPlatform.h \
		/opt/spinnaker/include/SpinnakerDefs.h \
		/opt/spinnaker/include/SpinGenApi/GCBase.h \
		/opt/spinnaker/include/SpinGenApi/GCTypes.h \
		/opt/spinnaker/include/SpinGenApi/GCString.h \
		/opt/spinnaker/include/SpinGenApi/GCStringVector.h \
		/opt/spinnaker/include/SpinGenApi/GCUtilities.h \
		/opt/spinnaker/include/SpinGenApi/SpinnakerGenApi.h \
		/opt/spinnaker/include/SpinGenApi/Node.h \
		/opt/spinnaker/include/SpinGenApi/Types.h \
		/opt/spinnaker/include/SpinGenApi/Autovector.h \
		/opt/spinnaker/include/SpinGenApi/Base.h \
		/opt/spinnaker/include/SpinGenApi/Container.h \
		/opt/spinnaker/include/SpinGenApi/ISelector.h \
		/opt/spinnaker/include/SpinGenApi/INode.h \
		/opt/spinnaker/include/SpinGenApi/Reference.h \
		/opt/spinnaker/include/SpinGenApi/NodeMap.h \
		/opt/spinnaker/include/SpinGenApi/INodeMap.h \
		/opt/spinnaker/include/SpinGenApi/IPort.h \
		/opt/spinnaker/include/SpinGenApi/Synch.h \
		/opt/spinnaker/include/SpinGenApi/IDeviceInfo.h \
		/opt/spinnaker/include/SpinGenApi/ValueNode.h \
		/opt/spinnaker/include/SpinGenApi/IValue.h \
		/opt/spinnaker/include/SpinGenApi/EnumNodeT.h \
		/opt/spinnaker/include/SpinGenApi/EnumNode.h \
		/opt/spinnaker/include/SpinGenApi/IEnumeration.h \
		/opt/spinnaker/include/SpinGenApi/IEnumEntry.h \
		/opt/spinnaker/include/SpinGenApi/IEnumerationT.h \
		/opt/spinnaker/include/SpinGenApi/Pointer.h \
		/opt/spinnaker/include/SpinGenApi/ICategory.h \
		/opt/spinnaker/include/SpinGenApi/IInteger.h \
		/opt/spinnaker/include/SpinGenApi/IFloat.h \
		/opt/spinnaker/include/SpinGenApi/IRegister.h \
		/opt/spinnaker/include/SpinGenApi/IBoolean.h \
		/opt/spinnaker/include/SpinGenApi/IPortRecorder.h \
		/opt/spinnaker/include/SpinGenApi/IPortConstruct.h \
		/opt/spinnaker/include/SpinGenApi/IChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/IString.h \
		/opt/spinnaker/include/SpinGenApi/INodeMapDyn.h \
		/opt/spinnaker/include/SpinGenApi/IDestroy.h \
		/opt/spinnaker/include/SpinGenApi/ICommand.h \
		/opt/spinnaker/include/Exception.h \
		/opt/spinnaker/include/SpinGenApi/EnumEntryNode.h \
		/opt/spinnaker/include/SpinGenApi/PortNode.h \
		/opt/spinnaker/include/SpinGenApi/IntegerNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatNode.h \
		/opt/spinnaker/include/SpinGenApi/StringNode.h \
		/opt/spinnaker/include/SpinGenApi/BooleanNode.h \
		/opt/spinnaker/include/SpinGenApi/NodeCallback.h \
		/opt/spinnaker/include/SpinGenApi/EnumClasses.h \
		/opt/spinnaker/include/SpinGenApi/CategoryNode.h \
		/opt/spinnaker/include/SpinGenApi/CommandNode.h \
		/opt/spinnaker/include/SpinGenApi/RegisterNode.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapter.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterDcam.h \
		/opt/spinnaker/include/SpinGenApi/Compatibility.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/ChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter.h \
		/opt/spinnaker/include/SpinGenApi/EventPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter1394.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/IntRegNode.h \
		/opt/spinnaker/include/SpinGenApi/StringRegNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatRegNode.h \
		/opt/spinnaker/include/SpinGenApi/PortWriteList.h \
		/opt/spinnaker/include/SpinGenApi/Persistence.h \
		/opt/spinnaker/include/SpinGenApi/ISelectorDigit.h \
		/opt/spinnaker/include/SpinGenApi/Filestream.h \
		/opt/spinnaker/include/System.h \
		/opt/spinnaker/include/Interface/ISystem.h \
		/opt/spinnaker/include/InterfaceList.h \
		/opt/spinnaker/include/Interface/IInterfaceList.h \
		/opt/spinnaker/include/InterfacePtr.h \
		/opt/spinnaker/include/BasePtr.h \
		/opt/spinnaker/include/Interface.h \
		/opt/spinnaker/include/Interface/IInterface.h \
		/opt/spinnaker/include/CameraList.h \
		/opt/spinnaker/include/Interface/ICameraList.h \
		/opt/spinnaker/include/Camera.h \
		/opt/spinnaker/include/CameraBase.h \
		/opt/spinnaker/include/Interface/ICameraBase.h \
		/opt/spinnaker/include/TransportLayerStream.h \
		/opt/spinnaker/include/TransportLayerDefs.h \
		/opt/spinnaker/include/TransportLayerDevice.h \
		/opt/spinnaker/include/EventHandler.h \
		/opt/spinnaker/include/Interface/IImageList.h \
		/opt/spinnaker/include/Image.h \
		/opt/spinnaker/include/Interface/IImage.h \
		/opt/spinnaker/include/CameraDefs.h \
		/opt/spinnaker/include/ChunkData.h \
		/opt/spinnaker/include/Interface/IChunkData.h \
		/opt/spinnaker/include/ChunkDataInference.h \
		/opt/spinnaker/include/ImagePtr.h \
		/opt/spinnaker/include/CameraPtr.h \
		/opt/spinnaker/include/TransportLayerInterface.h \
		/opt/spinnaker/include/TransportLayerSystem.h \
		/opt/spinnaker/include/LoggingEventHandler.h \
		/opt/spinnaker/include/Interface/ILoggingEventHandler.h \
		/opt/spinnaker/include/LoggingEventDataPtr.h \
		/opt/spinnaker/include/LoggingEventData.h \
		/opt/spinnaker/include/SystemPtr.h \
		/opt/spinnaker/include/ImageProcessor.h \
		/opt/spinnaker/include/Interface/IImageProcessor.h \
		/opt/spinnaker/include/ImageStatistics.h \
		/opt/spinnaker/include/Interface/IImageStatistics.h \
		/opt/spinnaker/include/ImageList.h \
		/opt/spinnaker/include/InterfaceEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceEventHandler.h \
		/opt/spinnaker/include/DeviceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceArrivalEventHandler.h \
		/opt/spinnaker/include/DeviceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceRemovalEventHandler.h \
		/opt/spinnaker/include/DeviceEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceEventHandler.h \
		/opt/spinnaker/include/ImageEventHandler.h \
		/opt/spinnaker/include/Interface/IImageEventHandler.h \
		/opt/spinnaker/include/ImageListEventHandler.h \
		/opt/spinnaker/include/Interface/IImageListEventHandler.h \
		/opt/spinnaker/include/InterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/InterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/SystemEventHandler.h \
		/opt/spinnaker/include/Interface/ISystemEventHandler.h \
		/opt/spinnaker/include/DeviceEventUtility.h \
		/opt/spinnaker/include/ImageUtility.h \
		/opt/spinnaker/include/ImageUtilityCCM.h \
		/opt/spinnaker/include/ImageUtilityHeatmap.h \
		/opt/spinnaker/include/ImageUtilityPolarization.h \
		../../../anaconda3/include/qt/QtGui/QImage \
		../../../anaconda3/include/qt/QtGui/qimage.h \
		../../../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtGui/qtgui-config.h \
		../../../anaconda3/include/qt/QtGui/qcolor.h \
		../../../anaconda3/include/qt/QtGui/qrgb.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qstringliteral.h \
		../../../anaconda3/include/qt/QtCore/qstringalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qstringview.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtCore/qcontainertools_impl.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda3/include/qt/QtCore/qrect.h \
		../../../anaconda3/include/qt/QtCore/qmargins.h \
		../../../anaconda3/include/qt/QtCore/qsize.h \
		../../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../../anaconda3/include/qt/QtGui/qtransform.h \
		../../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../../anaconda3/include/qt/QtGui/qregion.h \
		../../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtCore/qline.h \
		src/cuda_functions.h \
		../../../anaconda3/include/qt/QtWidgets/QWidget \
		../../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../../anaconda3/include/qt/QtGui/qpalette.h \
		../../../anaconda3/include/qt/QtGui/qbrush.h \
		../../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtGui/qfont.h \
		../../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../../anaconda3/include/qt/QtGui/qcursor.h \
		../../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../../anaconda3/include/qt/QtGui/qevent.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qurl.h \
		../../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../../anaconda3/include/qt/QtCore/qfile.h \
		../../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../../anaconda3/include/qt/QtWidgets/QPushButton \
		../../../anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../../../anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../../../anaconda3/include/qt/QtGui/qicon.h \
		../../../anaconda3/include/qt/QtWidgets/QLineEdit \
		../../../anaconda3/include/qt/QtWidgets/qlineedit.h \
		../../../anaconda3/include/qt/QtWidgets/qframe.h \
		../../../anaconda3/include/qt/QtGui/qtextcursor.h \
		../../../anaconda3/include/qt/QtGui/qtextformat.h \
		../../../anaconda3/include/qt/QtGui/qpen.h \
		../../../anaconda3/include/qt/QtGui/qtextoption.h \
		../../../anaconda3/include/qt/QtWidgets/QFileDialog \
		../../../anaconda3/include/qt/QtWidgets/qfiledialog.h \
		../../../anaconda3/include/qt/QtCore/qdir.h \
		../../../anaconda3/include/qt/QtCore/qfileinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qdialog.h \
		../../../anaconda3/include/qt/QtWidgets/QVBoxLayout \
		../../../anaconda3/include/qt/QtWidgets/qboxlayout.h \
		../../../anaconda3/include/qt/QtWidgets/qlayout.h \
		../../../anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../../../anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../../../anaconda3/include/qt/QtWidgets/QHBoxLayout \
		../../../anaconda3/include/qt/QtCore/QDebug \
		../../../anaconda3/include/qt/QtWidgets/QLabel \
		../../../anaconda3/include/qt/QtWidgets/qlabel.h \
		../../../anaconda3/include/qt/QtCore/QTimer \
		../../../anaconda3/include/qt/QtCore/qtimer.h \
		../../../anaconda3/include/qt/QtCore/qbasictimer.h \
		../../../anaconda3/include/qt/QtConcurrent/QtConcurrent \
		../../../anaconda3/include/qt/QtConcurrent/QtConcurrentDepends \
		../../../anaconda3/include/qt/QtCore/QtCore \
		../../../anaconda3/include/qt/QtCore/QtCoreDepends \
		../../../anaconda3/include/qt/QtCore/qabstractanimation.h \
		../../../anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		../../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../../anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		../../../anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractstate.h \
		../../../anaconda3/include/qt/QtCore/qabstracttransition.h \
		../../../anaconda3/include/qt/QtCore/qanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qarraydataops.h \
		../../../anaconda3/include/qt/QtCore/qarraydatapointer.h \
		../../../anaconda3/include/qt/QtCore/qbitarray.h \
		../../../anaconda3/include/qt/QtCore/qbuffer.h \
		../../../anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		../../../anaconda3/include/qt/QtCore/qcache.h \
		../../../anaconda3/include/qt/QtCore/qcalendar.h \
		../../../anaconda3/include/qt/QtCore/qcborarray.h \
		../../../anaconda3/include/qt/QtCore/qcborvalue.h \
		../../../anaconda3/include/qt/QtCore/qdatetime.h \
		../../../anaconda3/include/qt/QtCore/qcborcommon.h \
		../../../anaconda3/include/qt/QtCore/qregularexpression.h \
		../../../anaconda3/include/qt/QtCore/quuid.h \
		../../../anaconda3/include/qt/QtCore/qcbormap.h \
		../../../anaconda3/include/qt/QtCore/qcborstream.h \
		../../../anaconda3/include/qt/QtCore/qcborstreamreader.h \
		../../../anaconda3/include/qt/QtCore/qfloat16.h \
		../../../anaconda3/include/qt/QtCore/qcborstreamwriter.h \
		../../../anaconda3/include/qt/QtCore/qcollator.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineoption.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineparser.h \
		../../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../../anaconda3/include/qt/QtCore/qconcatenatetablesproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qcryptographichash.h \
		../../../anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		../../../anaconda3/include/qt/QtCore/qelapsedtimer.h \
		../../../anaconda3/include/qt/QtCore/qdiriterator.h \
		../../../anaconda3/include/qt/QtCore/qeasingcurve.h \
		../../../anaconda3/include/qt/QtCore/qendian.h \
		../../../anaconda3/include/qt/QtCore/qeventtransition.h \
		../../../anaconda3/include/qt/QtCore/qexception.h \
		../../../anaconda3/include/qt/QtCore/qfactoryinterface.h \
		../../../anaconda3/include/qt/QtCore/qfileselector.h \
		../../../anaconda3/include/qt/QtCore/QObject \
		../../../anaconda3/include/qt/QtCore/QStringList \
		../../../anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		../../../anaconda3/include/qt/QtCore/qfinalstate.h \
		../../../anaconda3/include/qt/QtCore/qfuture.h \
		../../../anaconda3/include/qt/QtCore/qfutureinterface.h \
		../../../anaconda3/include/qt/QtCore/qrunnable.h \
		../../../anaconda3/include/qt/QtCore/qresultstore.h \
		../../../anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		../../../anaconda3/include/qt/QtCore/qfuturewatcher.h \
		../../../anaconda3/include/qt/QtCore/qhistorystate.h \
		../../../anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qisenum.h \
		../../../anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		../../../anaconda3/include/qt/QtCore/qjsonarray.h \
		../../../anaconda3/include/qt/QtCore/qjsonvalue.h \
		../../../anaconda3/include/qt/QtCore/qjsondocument.h \
		../../../anaconda3/include/qt/QtCore/qjsonobject.h \
		../../../anaconda3/include/qt/QtCore/qlibrary.h \
		../../../anaconda3/include/qt/QtCore/qlibraryinfo.h \
		../../../anaconda3/include/qt/QtCore/qversionnumber.h \
		../../../anaconda3/include/qt/QtCore/qlinkedlist.h \
		../../../anaconda3/include/qt/QtCore/qlockfile.h \
		../../../anaconda3/include/qt/QtCore/qloggingcategory.h \
		../../../anaconda3/include/qt/QtCore/qmath.h \
		../../../anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		../../../anaconda3/include/qt/QtCore/qmetaobject.h \
		../../../anaconda3/include/qt/QtCore/qmimedata.h \
		../../../anaconda3/include/qt/QtCore/qmimedatabase.h \
		../../../anaconda3/include/qt/QtCore/qmimetype.h \
		../../../anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		../../../anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		../../../anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qpauseanimation.h \
		../../../anaconda3/include/qt/QtCore/qplugin.h \
		../../../anaconda3/include/qt/QtCore/qpointer.h \
		../../../anaconda3/include/qt/QtCore/qpluginloader.h \
		../../../anaconda3/include/qt/QtCore/qprocess.h \
		../../../anaconda3/include/qt/QtCore/qpropertyanimation.h \
		../../../anaconda3/include/qt/QtCore/qvariantanimation.h \
		../../../anaconda3/include/qt/QtCore/qqueue.h \
		../../../anaconda3/include/qt/QtCore/qrandom.h \
		../../../anaconda3/include/qt/QtCore/qreadwritelock.h \
		../../../anaconda3/include/qt/QtCore/qresource.h \
		../../../anaconda3/include/qt/QtCore/qsavefile.h \
		../../../anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		../../../anaconda3/include/qt/QtCore/qscopeguard.h \
		../../../anaconda3/include/qt/QtCore/qsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qsettings.h \
		../../../anaconda3/include/qt/QtCore/qsharedmemory.h \
		../../../anaconda3/include/qt/QtCore/qsignalmapper.h \
		../../../anaconda3/include/qt/QtCore/qsignaltransition.h \
		../../../anaconda3/include/qt/QtCore/qsocketnotifier.h \
		../../../anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qstack.h \
		../../../anaconda3/include/qt/QtCore/qstandardpaths.h \
		../../../anaconda3/include/qt/QtCore/qstate.h \
		../../../anaconda3/include/qt/QtCore/qstatemachine.h \
		../../../anaconda3/include/qt/QtCore/qstorageinfo.h \
		../../../anaconda3/include/qt/QtCore/qstringlistmodel.h \
		../../../anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qtemporarydir.h \
		../../../anaconda3/include/qt/QtCore/qtemporaryfile.h \
		../../../anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		../../../anaconda3/include/qt/QtCore/qtextcodec.h \
		../../../anaconda3/include/qt/QtCore/qthread.h \
		../../../anaconda3/include/qt/QtCore/qthreadpool.h \
		../../../anaconda3/include/qt/QtCore/qthreadstorage.h \
		../../../anaconda3/include/qt/QtCore/qtimeline.h \
		../../../anaconda3/include/qt/QtCore/qtimezone.h \
		../../../anaconda3/include/qt/QtCore/qtranslator.h \
		../../../anaconda3/include/qt/QtCore/qtransposeproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../../anaconda3/include/qt/QtCore/qwaitcondition.h \
		../../../anaconda3/include/qt/QtCore/QDeadlineTimer \
		../../../anaconda3/include/qt/QtCore/qwineventnotifier.h \
		../../../anaconda3/include/qt/QtCore/qxmlstream.h \
		../../../anaconda3/include/qt/QtCore/qtcoreversion.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentcompilertest.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrent_global.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentexception.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentfilter.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentfilterkernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentiteratekernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentmedian.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentthreadengine.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentmapkernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentreducekernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentfunctionwrappers.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentmap.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentrun.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentrunbase.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentstoredfunctioncall.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentversion.h \
		../../../anaconda3/include/qt/QtWidgets/QMessageBox \
		../../../anaconda3/include/qt/QtWidgets/qmessagebox.h \
		../../../anaconda3/include/qt/QtCharts/QChartView \
		../../../anaconda3/include/qt/QtCharts/qchartview.h \
		../../../anaconda3/include/qt/QtCharts/QAbstractAxis \
		../../../anaconda3/include/qt/QtCharts/qabstractaxis.h \
		../../../anaconda3/include/qt/QtCharts/QChartGlobal \
		../../../anaconda3/include/qt/QtCharts/qchartglobal.h \
		../../../anaconda3/include/qt/QtCore/QtGlobal \
		../../../anaconda3/include/qt/QtGui/QPen \
		../../../anaconda3/include/qt/QtGui/QFont \
		../../../anaconda3/include/qt/QtCore/QVariant \
		../../../anaconda3/include/qt/QtCharts/QAbstractSeries \
		../../../anaconda3/include/qt/QtCharts/qabstractseries.h \
		../../../anaconda3/include/qt/QtCharts/QChart \
		../../../anaconda3/include/qt/QtCharts/qchart.h \
		../../../anaconda3/include/qt/QtCharts/QLegend \
		../../../anaconda3/include/qt/QtCharts/qlegend.h \
		../../../anaconda3/include/qt/QtWidgets/QGraphicsWidget \
		../../../anaconda3/include/qt/QtWidgets/qgraphicswidget.h \
		../../../anaconda3/include/qt/QtWidgets/qgraphicslayoutitem.h \
		../../../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../../anaconda3/include/qt/QtGui/QBrush \
		../../../anaconda3/include/qt/QtCore/QMargins \
		../../../anaconda3/include/qt/QtWidgets/QGraphicsView \
		../../../anaconda3/include/qt/QtWidgets/qgraphicsview.h \
		../../../anaconda3/include/qt/QtGui/qpainter.h \
		../../../anaconda3/include/qt/QtWidgets/qscrollarea.h \
		../../../anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		../../../anaconda3/include/qt/QtWidgets/qgraphicsscene.h \
		../../../anaconda3/include/qt/QtCharts/QLineSeries \
		../../../anaconda3/include/qt/QtCharts/qlineseries.h \
		../../../anaconda3/include/qt/QtCharts/QXYSeries \
		../../../anaconda3/include/qt/QtCharts/qxyseries.h \
		../../../anaconda3/include/qt/QtCharts/QValueAxis \
		../../../anaconda3/include/qt/QtCharts/qvalueaxis.h \
		../../../anaconda3/include/qt/QtCore/QThreadPool \
		moc/moc_predefs.h \
		../../../anaconda3/bin/moc
	/home/dai/anaconda3/bin/moc $(DEFINES) --include /home/dai/Documents/repos/JetsonCamApp/moc/moc_predefs.h -I/home/dai/anaconda3/mkspecs/linux-g++ -I/home/dai/Documents/repos/JetsonCamApp -I/usr/local/cuda/include -I/opt/spinnaker/include -I/home/dai/anaconda3/include/qt -I/home/dai/anaconda3/include/qt/QtCharts -I/home/dai/anaconda3/include/qt/QtWidgets -I/home/dai/anaconda3/include/qt/QtGui -I/home/dai/anaconda3/include/qt/QtConcurrent -I/home/dai/anaconda3/include/qt/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/appwindow.h -o moc/moc_appwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/main.o: src/main.cpp src/appwindow.h \
		src/camerahandler.h \
		/opt/spinnaker/include/Spinnaker.h \
		/opt/spinnaker/include/SpinnakerPlatform.h \
		/opt/spinnaker/include/SpinnakerDefs.h \
		/opt/spinnaker/include/SpinGenApi/GCBase.h \
		/opt/spinnaker/include/SpinGenApi/GCTypes.h \
		/opt/spinnaker/include/SpinGenApi/GCString.h \
		/opt/spinnaker/include/SpinGenApi/GCStringVector.h \
		/opt/spinnaker/include/SpinGenApi/GCUtilities.h \
		/opt/spinnaker/include/SpinGenApi/SpinnakerGenApi.h \
		/opt/spinnaker/include/SpinGenApi/Node.h \
		/opt/spinnaker/include/SpinGenApi/Types.h \
		/opt/spinnaker/include/SpinGenApi/Autovector.h \
		/opt/spinnaker/include/SpinGenApi/Base.h \
		/opt/spinnaker/include/SpinGenApi/Container.h \
		/opt/spinnaker/include/SpinGenApi/ISelector.h \
		/opt/spinnaker/include/SpinGenApi/INode.h \
		/opt/spinnaker/include/SpinGenApi/Reference.h \
		/opt/spinnaker/include/SpinGenApi/NodeMap.h \
		/opt/spinnaker/include/SpinGenApi/INodeMap.h \
		/opt/spinnaker/include/SpinGenApi/IPort.h \
		/opt/spinnaker/include/SpinGenApi/Synch.h \
		/opt/spinnaker/include/SpinGenApi/IDeviceInfo.h \
		/opt/spinnaker/include/SpinGenApi/ValueNode.h \
		/opt/spinnaker/include/SpinGenApi/IValue.h \
		/opt/spinnaker/include/SpinGenApi/EnumNodeT.h \
		/opt/spinnaker/include/SpinGenApi/EnumNode.h \
		/opt/spinnaker/include/SpinGenApi/IEnumeration.h \
		/opt/spinnaker/include/SpinGenApi/IEnumEntry.h \
		/opt/spinnaker/include/SpinGenApi/IEnumerationT.h \
		/opt/spinnaker/include/SpinGenApi/Pointer.h \
		/opt/spinnaker/include/SpinGenApi/ICategory.h \
		/opt/spinnaker/include/SpinGenApi/IInteger.h \
		/opt/spinnaker/include/SpinGenApi/IFloat.h \
		/opt/spinnaker/include/SpinGenApi/IRegister.h \
		/opt/spinnaker/include/SpinGenApi/IBoolean.h \
		/opt/spinnaker/include/SpinGenApi/IPortRecorder.h \
		/opt/spinnaker/include/SpinGenApi/IPortConstruct.h \
		/opt/spinnaker/include/SpinGenApi/IChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/IString.h \
		/opt/spinnaker/include/SpinGenApi/INodeMapDyn.h \
		/opt/spinnaker/include/SpinGenApi/IDestroy.h \
		/opt/spinnaker/include/SpinGenApi/ICommand.h \
		/opt/spinnaker/include/Exception.h \
		/opt/spinnaker/include/SpinGenApi/EnumEntryNode.h \
		/opt/spinnaker/include/SpinGenApi/PortNode.h \
		/opt/spinnaker/include/SpinGenApi/IntegerNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatNode.h \
		/opt/spinnaker/include/SpinGenApi/StringNode.h \
		/opt/spinnaker/include/SpinGenApi/BooleanNode.h \
		/opt/spinnaker/include/SpinGenApi/NodeCallback.h \
		/opt/spinnaker/include/SpinGenApi/EnumClasses.h \
		/opt/spinnaker/include/SpinGenApi/CategoryNode.h \
		/opt/spinnaker/include/SpinGenApi/CommandNode.h \
		/opt/spinnaker/include/SpinGenApi/RegisterNode.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapter.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterDcam.h \
		/opt/spinnaker/include/SpinGenApi/Compatibility.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/ChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter.h \
		/opt/spinnaker/include/SpinGenApi/EventPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter1394.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/IntRegNode.h \
		/opt/spinnaker/include/SpinGenApi/StringRegNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatRegNode.h \
		/opt/spinnaker/include/SpinGenApi/PortWriteList.h \
		/opt/spinnaker/include/SpinGenApi/Persistence.h \
		/opt/spinnaker/include/SpinGenApi/ISelectorDigit.h \
		/opt/spinnaker/include/SpinGenApi/Filestream.h \
		/opt/spinnaker/include/System.h \
		/opt/spinnaker/include/Interface/ISystem.h \
		/opt/spinnaker/include/InterfaceList.h \
		/opt/spinnaker/include/Interface/IInterfaceList.h \
		/opt/spinnaker/include/InterfacePtr.h \
		/opt/spinnaker/include/BasePtr.h \
		/opt/spinnaker/include/Interface.h \
		/opt/spinnaker/include/Interface/IInterface.h \
		/opt/spinnaker/include/CameraList.h \
		/opt/spinnaker/include/Interface/ICameraList.h \
		/opt/spinnaker/include/Camera.h \
		/opt/spinnaker/include/CameraBase.h \
		/opt/spinnaker/include/Interface/ICameraBase.h \
		/opt/spinnaker/include/TransportLayerStream.h \
		/opt/spinnaker/include/TransportLayerDefs.h \
		/opt/spinnaker/include/TransportLayerDevice.h \
		/opt/spinnaker/include/EventHandler.h \
		/opt/spinnaker/include/Interface/IImageList.h \
		/opt/spinnaker/include/Image.h \
		/opt/spinnaker/include/Interface/IImage.h \
		/opt/spinnaker/include/CameraDefs.h \
		/opt/spinnaker/include/ChunkData.h \
		/opt/spinnaker/include/Interface/IChunkData.h \
		/opt/spinnaker/include/ChunkDataInference.h \
		/opt/spinnaker/include/ImagePtr.h \
		/opt/spinnaker/include/CameraPtr.h \
		/opt/spinnaker/include/TransportLayerInterface.h \
		/opt/spinnaker/include/TransportLayerSystem.h \
		/opt/spinnaker/include/LoggingEventHandler.h \
		/opt/spinnaker/include/Interface/ILoggingEventHandler.h \
		/opt/spinnaker/include/LoggingEventDataPtr.h \
		/opt/spinnaker/include/LoggingEventData.h \
		/opt/spinnaker/include/SystemPtr.h \
		/opt/spinnaker/include/ImageProcessor.h \
		/opt/spinnaker/include/Interface/IImageProcessor.h \
		/opt/spinnaker/include/ImageStatistics.h \
		/opt/spinnaker/include/Interface/IImageStatistics.h \
		/opt/spinnaker/include/ImageList.h \
		/opt/spinnaker/include/InterfaceEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceEventHandler.h \
		/opt/spinnaker/include/DeviceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceArrivalEventHandler.h \
		/opt/spinnaker/include/DeviceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceRemovalEventHandler.h \
		/opt/spinnaker/include/DeviceEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceEventHandler.h \
		/opt/spinnaker/include/ImageEventHandler.h \
		/opt/spinnaker/include/Interface/IImageEventHandler.h \
		/opt/spinnaker/include/ImageListEventHandler.h \
		/opt/spinnaker/include/Interface/IImageListEventHandler.h \
		/opt/spinnaker/include/InterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/InterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/SystemEventHandler.h \
		/opt/spinnaker/include/Interface/ISystemEventHandler.h \
		/opt/spinnaker/include/DeviceEventUtility.h \
		/opt/spinnaker/include/ImageUtility.h \
		/opt/spinnaker/include/ImageUtilityCCM.h \
		/opt/spinnaker/include/ImageUtilityHeatmap.h \
		/opt/spinnaker/include/ImageUtilityPolarization.h \
		../../../anaconda3/include/qt/QtGui/QImage \
		../../../anaconda3/include/qt/QtGui/qimage.h \
		../../../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtGui/qtgui-config.h \
		../../../anaconda3/include/qt/QtGui/qcolor.h \
		../../../anaconda3/include/qt/QtGui/qrgb.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qstringliteral.h \
		../../../anaconda3/include/qt/QtCore/qstringalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qstringview.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtCore/qcontainertools_impl.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda3/include/qt/QtCore/qrect.h \
		../../../anaconda3/include/qt/QtCore/qmargins.h \
		../../../anaconda3/include/qt/QtCore/qsize.h \
		../../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../../anaconda3/include/qt/QtGui/qtransform.h \
		../../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../../anaconda3/include/qt/QtGui/qregion.h \
		../../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtCore/qline.h \
		src/cuda_functions.h \
		../../../anaconda3/include/qt/QtWidgets/QWidget \
		../../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../../anaconda3/include/qt/QtGui/qpalette.h \
		../../../anaconda3/include/qt/QtGui/qbrush.h \
		../../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtGui/qfont.h \
		../../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../../anaconda3/include/qt/QtGui/qcursor.h \
		../../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../../anaconda3/include/qt/QtGui/qevent.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qurl.h \
		../../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../../anaconda3/include/qt/QtCore/qfile.h \
		../../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../../anaconda3/include/qt/QtWidgets/QPushButton \
		../../../anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../../../anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../../../anaconda3/include/qt/QtGui/qicon.h \
		../../../anaconda3/include/qt/QtWidgets/QLineEdit \
		../../../anaconda3/include/qt/QtWidgets/qlineedit.h \
		../../../anaconda3/include/qt/QtWidgets/qframe.h \
		../../../anaconda3/include/qt/QtGui/qtextcursor.h \
		../../../anaconda3/include/qt/QtGui/qtextformat.h \
		../../../anaconda3/include/qt/QtGui/qpen.h \
		../../../anaconda3/include/qt/QtGui/qtextoption.h \
		../../../anaconda3/include/qt/QtWidgets/QFileDialog \
		../../../anaconda3/include/qt/QtWidgets/qfiledialog.h \
		../../../anaconda3/include/qt/QtCore/qdir.h \
		../../../anaconda3/include/qt/QtCore/qfileinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qdialog.h \
		../../../anaconda3/include/qt/QtWidgets/QVBoxLayout \
		../../../anaconda3/include/qt/QtWidgets/qboxlayout.h \
		../../../anaconda3/include/qt/QtWidgets/qlayout.h \
		../../../anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../../../anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../../../anaconda3/include/qt/QtWidgets/QHBoxLayout \
		../../../anaconda3/include/qt/QtCore/QDebug \
		../../../anaconda3/include/qt/QtWidgets/QLabel \
		../../../anaconda3/include/qt/QtWidgets/qlabel.h \
		../../../anaconda3/include/qt/QtCore/QTimer \
		../../../anaconda3/include/qt/QtCore/qtimer.h \
		../../../anaconda3/include/qt/QtCore/qbasictimer.h \
		../../../anaconda3/include/qt/QtConcurrent/QtConcurrent \
		../../../anaconda3/include/qt/QtConcurrent/QtConcurrentDepends \
		../../../anaconda3/include/qt/QtCore/QtCore \
		../../../anaconda3/include/qt/QtCore/QtCoreDepends \
		../../../anaconda3/include/qt/QtCore/qabstractanimation.h \
		../../../anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		../../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../../anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		../../../anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractstate.h \
		../../../anaconda3/include/qt/QtCore/qabstracttransition.h \
		../../../anaconda3/include/qt/QtCore/qanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qarraydataops.h \
		../../../anaconda3/include/qt/QtCore/qarraydatapointer.h \
		../../../anaconda3/include/qt/QtCore/qbitarray.h \
		../../../anaconda3/include/qt/QtCore/qbuffer.h \
		../../../anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		../../../anaconda3/include/qt/QtCore/qcache.h \
		../../../anaconda3/include/qt/QtCore/qcalendar.h \
		../../../anaconda3/include/qt/QtCore/qcborarray.h \
		../../../anaconda3/include/qt/QtCore/qcborvalue.h \
		../../../anaconda3/include/qt/QtCore/qdatetime.h \
		../../../anaconda3/include/qt/QtCore/qcborcommon.h \
		../../../anaconda3/include/qt/QtCore/qregularexpression.h \
		../../../anaconda3/include/qt/QtCore/quuid.h \
		../../../anaconda3/include/qt/QtCore/qcbormap.h \
		../../../anaconda3/include/qt/QtCore/qcborstream.h \
		../../../anaconda3/include/qt/QtCore/qcborstreamreader.h \
		../../../anaconda3/include/qt/QtCore/qfloat16.h \
		../../../anaconda3/include/qt/QtCore/qcborstreamwriter.h \
		../../../anaconda3/include/qt/QtCore/qcollator.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineoption.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineparser.h \
		../../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../../anaconda3/include/qt/QtCore/qconcatenatetablesproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qcryptographichash.h \
		../../../anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		../../../anaconda3/include/qt/QtCore/qelapsedtimer.h \
		../../../anaconda3/include/qt/QtCore/qdiriterator.h \
		../../../anaconda3/include/qt/QtCore/qeasingcurve.h \
		../../../anaconda3/include/qt/QtCore/qendian.h \
		../../../anaconda3/include/qt/QtCore/qeventtransition.h \
		../../../anaconda3/include/qt/QtCore/qexception.h \
		../../../anaconda3/include/qt/QtCore/qfactoryinterface.h \
		../../../anaconda3/include/qt/QtCore/qfileselector.h \
		../../../anaconda3/include/qt/QtCore/QObject \
		../../../anaconda3/include/qt/QtCore/QStringList \
		../../../anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		../../../anaconda3/include/qt/QtCore/qfinalstate.h \
		../../../anaconda3/include/qt/QtCore/qfuture.h \
		../../../anaconda3/include/qt/QtCore/qfutureinterface.h \
		../../../anaconda3/include/qt/QtCore/qrunnable.h \
		../../../anaconda3/include/qt/QtCore/qresultstore.h \
		../../../anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		../../../anaconda3/include/qt/QtCore/qfuturewatcher.h \
		../../../anaconda3/include/qt/QtCore/qhistorystate.h \
		../../../anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qisenum.h \
		../../../anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		../../../anaconda3/include/qt/QtCore/qjsonarray.h \
		../../../anaconda3/include/qt/QtCore/qjsonvalue.h \
		../../../anaconda3/include/qt/QtCore/qjsondocument.h \
		../../../anaconda3/include/qt/QtCore/qjsonobject.h \
		../../../anaconda3/include/qt/QtCore/qlibrary.h \
		../../../anaconda3/include/qt/QtCore/qlibraryinfo.h \
		../../../anaconda3/include/qt/QtCore/qversionnumber.h \
		../../../anaconda3/include/qt/QtCore/qlinkedlist.h \
		../../../anaconda3/include/qt/QtCore/qlockfile.h \
		../../../anaconda3/include/qt/QtCore/qloggingcategory.h \
		../../../anaconda3/include/qt/QtCore/qmath.h \
		../../../anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		../../../anaconda3/include/qt/QtCore/qmetaobject.h \
		../../../anaconda3/include/qt/QtCore/qmimedata.h \
		../../../anaconda3/include/qt/QtCore/qmimedatabase.h \
		../../../anaconda3/include/qt/QtCore/qmimetype.h \
		../../../anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		../../../anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		../../../anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qpauseanimation.h \
		../../../anaconda3/include/qt/QtCore/qplugin.h \
		../../../anaconda3/include/qt/QtCore/qpointer.h \
		../../../anaconda3/include/qt/QtCore/qpluginloader.h \
		../../../anaconda3/include/qt/QtCore/qprocess.h \
		../../../anaconda3/include/qt/QtCore/qpropertyanimation.h \
		../../../anaconda3/include/qt/QtCore/qvariantanimation.h \
		../../../anaconda3/include/qt/QtCore/qqueue.h \
		../../../anaconda3/include/qt/QtCore/qrandom.h \
		../../../anaconda3/include/qt/QtCore/qreadwritelock.h \
		../../../anaconda3/include/qt/QtCore/qresource.h \
		../../../anaconda3/include/qt/QtCore/qsavefile.h \
		../../../anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		../../../anaconda3/include/qt/QtCore/qscopeguard.h \
		../../../anaconda3/include/qt/QtCore/qsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qsettings.h \
		../../../anaconda3/include/qt/QtCore/qsharedmemory.h \
		../../../anaconda3/include/qt/QtCore/qsignalmapper.h \
		../../../anaconda3/include/qt/QtCore/qsignaltransition.h \
		../../../anaconda3/include/qt/QtCore/qsocketnotifier.h \
		../../../anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qstack.h \
		../../../anaconda3/include/qt/QtCore/qstandardpaths.h \
		../../../anaconda3/include/qt/QtCore/qstate.h \
		../../../anaconda3/include/qt/QtCore/qstatemachine.h \
		../../../anaconda3/include/qt/QtCore/qstorageinfo.h \
		../../../anaconda3/include/qt/QtCore/qstringlistmodel.h \
		../../../anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qtemporarydir.h \
		../../../anaconda3/include/qt/QtCore/qtemporaryfile.h \
		../../../anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		../../../anaconda3/include/qt/QtCore/qtextcodec.h \
		../../../anaconda3/include/qt/QtCore/qthread.h \
		../../../anaconda3/include/qt/QtCore/qthreadpool.h \
		../../../anaconda3/include/qt/QtCore/qthreadstorage.h \
		../../../anaconda3/include/qt/QtCore/qtimeline.h \
		../../../anaconda3/include/qt/QtCore/qtimezone.h \
		../../../anaconda3/include/qt/QtCore/qtranslator.h \
		../../../anaconda3/include/qt/QtCore/qtransposeproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../../anaconda3/include/qt/QtCore/qwaitcondition.h \
		../../../anaconda3/include/qt/QtCore/QDeadlineTimer \
		../../../anaconda3/include/qt/QtCore/qwineventnotifier.h \
		../../../anaconda3/include/qt/QtCore/qxmlstream.h \
		../../../anaconda3/include/qt/QtCore/qtcoreversion.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentcompilertest.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrent_global.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentexception.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentfilter.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentfilterkernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentiteratekernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentmedian.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentthreadengine.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentmapkernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentreducekernel.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentfunctionwrappers.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentmap.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentrun.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentrunbase.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentstoredfunctioncall.h \
		../../../anaconda3/include/qt/QtConcurrent/qtconcurrentversion.h \
		../../../anaconda3/include/qt/QtWidgets/QMessageBox \
		../../../anaconda3/include/qt/QtWidgets/qmessagebox.h \
		../../../anaconda3/include/qt/QtCharts/QChartView \
		../../../anaconda3/include/qt/QtCharts/qchartview.h \
		../../../anaconda3/include/qt/QtCharts/QAbstractAxis \
		../../../anaconda3/include/qt/QtCharts/qabstractaxis.h \
		../../../anaconda3/include/qt/QtCharts/QChartGlobal \
		../../../anaconda3/include/qt/QtCharts/qchartglobal.h \
		../../../anaconda3/include/qt/QtCore/QtGlobal \
		../../../anaconda3/include/qt/QtGui/QPen \
		../../../anaconda3/include/qt/QtGui/QFont \
		../../../anaconda3/include/qt/QtCore/QVariant \
		../../../anaconda3/include/qt/QtCharts/QAbstractSeries \
		../../../anaconda3/include/qt/QtCharts/qabstractseries.h \
		../../../anaconda3/include/qt/QtCharts/QChart \
		../../../anaconda3/include/qt/QtCharts/qchart.h \
		../../../anaconda3/include/qt/QtCharts/QLegend \
		../../../anaconda3/include/qt/QtCharts/qlegend.h \
		../../../anaconda3/include/qt/QtWidgets/QGraphicsWidget \
		../../../anaconda3/include/qt/QtWidgets/qgraphicswidget.h \
		../../../anaconda3/include/qt/QtWidgets/qgraphicslayoutitem.h \
		../../../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../../anaconda3/include/qt/QtGui/QBrush \
		../../../anaconda3/include/qt/QtCore/QMargins \
		../../../anaconda3/include/qt/QtWidgets/QGraphicsView \
		../../../anaconda3/include/qt/QtWidgets/qgraphicsview.h \
		../../../anaconda3/include/qt/QtGui/qpainter.h \
		../../../anaconda3/include/qt/QtWidgets/qscrollarea.h \
		../../../anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		../../../anaconda3/include/qt/QtWidgets/qgraphicsscene.h \
		../../../anaconda3/include/qt/QtCharts/QLineSeries \
		../../../anaconda3/include/qt/QtCharts/qlineseries.h \
		../../../anaconda3/include/qt/QtCharts/QXYSeries \
		../../../anaconda3/include/qt/QtCharts/qxyseries.h \
		../../../anaconda3/include/qt/QtCharts/QValueAxis \
		../../../anaconda3/include/qt/QtCharts/qvalueaxis.h \
		../../../anaconda3/include/qt/QtCore/QThreadPool \
		../../../anaconda3/include/qt/QtWidgets/QApplication \
		../../../anaconda3/include/qt/QtWidgets/qapplication.h \
		../../../anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../../../anaconda3/include/qt/QtGui/qguiapplication.h \
		../../../anaconda3/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/moc_appwindow.o: moc/moc_appwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_appwindow.o moc/moc_appwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

