#############################################################################
# Makefile for building: jetsonCamApp
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  build.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile build.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/cuda/include -I/opt/spinnaker/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Imoc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = jetsonCamApp1.0.0
DISTDIR = /home/dai/Documents/JetsonCamApp/obj/jetsonCamApp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/opt/spinnaker/lib -lSpinnaker -L./obj -lcuda_functions -L/usr/local/cuda/lib64 -lcudart /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp moc/moc_appwindow.cpp
OBJECTS       = obj/main.o \
		obj/moc_appwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		build.pro src/appwindow.h \
		src/camerahandler.h src/main.cpp
QMAKE_TARGET  = jetsonCamApp
DESTDIR       = 
TARGET        = jetsonCamApp


first: all
####### Build rules

jetsonCamApp:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: build.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		build.pro
	$(QMAKE) -o Makefile build.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
build.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile build.pro

qmake_all: FORCE


all: Makefile jetsonCamApp

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/appwindow.h src/camerahandler.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_appwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_appwindow.cpp
moc/moc_appwindow.cpp: src/appwindow.h \
		src/camerahandler.h \
		/opt/spinnaker/include/Spinnaker.h \
		/opt/spinnaker/include/SpinnakerPlatform.h \
		/opt/spinnaker/include/SpinnakerDefs.h \
		/opt/spinnaker/include/SpinGenApi/GCBase.h \
		/opt/spinnaker/include/SpinGenApi/GCTypes.h \
		/opt/spinnaker/include/SpinGenApi/GCString.h \
		/opt/spinnaker/include/SpinGenApi/GCStringVector.h \
		/opt/spinnaker/include/SpinGenApi/GCUtilities.h \
		/opt/spinnaker/include/SpinGenApi/SpinnakerGenApi.h \
		/opt/spinnaker/include/SpinGenApi/Node.h \
		/opt/spinnaker/include/SpinGenApi/Types.h \
		/opt/spinnaker/include/SpinGenApi/Autovector.h \
		/opt/spinnaker/include/SpinGenApi/Base.h \
		/opt/spinnaker/include/SpinGenApi/Container.h \
		/opt/spinnaker/include/SpinGenApi/ISelector.h \
		/opt/spinnaker/include/SpinGenApi/INode.h \
		/opt/spinnaker/include/SpinGenApi/Reference.h \
		/opt/spinnaker/include/SpinGenApi/NodeMap.h \
		/opt/spinnaker/include/SpinGenApi/INodeMap.h \
		/opt/spinnaker/include/SpinGenApi/IPort.h \
		/opt/spinnaker/include/SpinGenApi/Synch.h \
		/opt/spinnaker/include/SpinGenApi/IDeviceInfo.h \
		/opt/spinnaker/include/SpinGenApi/ValueNode.h \
		/opt/spinnaker/include/SpinGenApi/IValue.h \
		/opt/spinnaker/include/SpinGenApi/EnumNodeT.h \
		/opt/spinnaker/include/SpinGenApi/EnumNode.h \
		/opt/spinnaker/include/SpinGenApi/IEnumeration.h \
		/opt/spinnaker/include/SpinGenApi/IEnumEntry.h \
		/opt/spinnaker/include/SpinGenApi/IEnumerationT.h \
		/opt/spinnaker/include/SpinGenApi/Pointer.h \
		/opt/spinnaker/include/SpinGenApi/ICategory.h \
		/opt/spinnaker/include/SpinGenApi/IInteger.h \
		/opt/spinnaker/include/SpinGenApi/IFloat.h \
		/opt/spinnaker/include/SpinGenApi/IRegister.h \
		/opt/spinnaker/include/SpinGenApi/IBoolean.h \
		/opt/spinnaker/include/SpinGenApi/IPortRecorder.h \
		/opt/spinnaker/include/SpinGenApi/IPortConstruct.h \
		/opt/spinnaker/include/SpinGenApi/IChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/IString.h \
		/opt/spinnaker/include/SpinGenApi/INodeMapDyn.h \
		/opt/spinnaker/include/SpinGenApi/IDestroy.h \
		/opt/spinnaker/include/SpinGenApi/ICommand.h \
		/opt/spinnaker/include/Exception.h \
		/opt/spinnaker/include/SpinGenApi/EnumEntryNode.h \
		/opt/spinnaker/include/SpinGenApi/PortNode.h \
		/opt/spinnaker/include/SpinGenApi/IntegerNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatNode.h \
		/opt/spinnaker/include/SpinGenApi/StringNode.h \
		/opt/spinnaker/include/SpinGenApi/BooleanNode.h \
		/opt/spinnaker/include/SpinGenApi/NodeCallback.h \
		/opt/spinnaker/include/SpinGenApi/EnumClasses.h \
		/opt/spinnaker/include/SpinGenApi/CategoryNode.h \
		/opt/spinnaker/include/SpinGenApi/CommandNode.h \
		/opt/spinnaker/include/SpinGenApi/RegisterNode.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapter.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterDcam.h \
		/opt/spinnaker/include/SpinGenApi/Compatibility.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/ChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter.h \
		/opt/spinnaker/include/SpinGenApi/EventPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter1394.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/IntRegNode.h \
		/opt/spinnaker/include/SpinGenApi/StringRegNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatRegNode.h \
		/opt/spinnaker/include/SpinGenApi/PortWriteList.h \
		/opt/spinnaker/include/SpinGenApi/Persistence.h \
		/opt/spinnaker/include/SpinGenApi/ISelectorDigit.h \
		/opt/spinnaker/include/SpinGenApi/Filestream.h \
		/opt/spinnaker/include/System.h \
		/opt/spinnaker/include/Interface/ISystem.h \
		/opt/spinnaker/include/InterfaceList.h \
		/opt/spinnaker/include/Interface/IInterfaceList.h \
		/opt/spinnaker/include/InterfacePtr.h \
		/opt/spinnaker/include/BasePtr.h \
		/opt/spinnaker/include/Interface.h \
		/opt/spinnaker/include/Interface/IInterface.h \
		/opt/spinnaker/include/CameraList.h \
		/opt/spinnaker/include/Interface/ICameraList.h \
		/opt/spinnaker/include/Camera.h \
		/opt/spinnaker/include/CameraBase.h \
		/opt/spinnaker/include/Interface/ICameraBase.h \
		/opt/spinnaker/include/TransportLayerStream.h \
		/opt/spinnaker/include/TransportLayerDefs.h \
		/opt/spinnaker/include/TransportLayerDevice.h \
		/opt/spinnaker/include/EventHandler.h \
		/opt/spinnaker/include/Interface/IImageList.h \
		/opt/spinnaker/include/Image.h \
		/opt/spinnaker/include/Interface/IImage.h \
		/opt/spinnaker/include/CameraDefs.h \
		/opt/spinnaker/include/ChunkData.h \
		/opt/spinnaker/include/Interface/IChunkData.h \
		/opt/spinnaker/include/ChunkDataInference.h \
		/opt/spinnaker/include/ImagePtr.h \
		/opt/spinnaker/include/CameraPtr.h \
		/opt/spinnaker/include/TransportLayerInterface.h \
		/opt/spinnaker/include/TransportLayerSystem.h \
		/opt/spinnaker/include/LoggingEventHandler.h \
		/opt/spinnaker/include/Interface/ILoggingEventHandler.h \
		/opt/spinnaker/include/LoggingEventDataPtr.h \
		/opt/spinnaker/include/LoggingEventData.h \
		/opt/spinnaker/include/SystemPtr.h \
		/opt/spinnaker/include/ImageProcessor.h \
		/opt/spinnaker/include/Interface/IImageProcessor.h \
		/opt/spinnaker/include/ImageStatistics.h \
		/opt/spinnaker/include/Interface/IImageStatistics.h \
		/opt/spinnaker/include/ImageList.h \
		/opt/spinnaker/include/InterfaceEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceEventHandler.h \
		/opt/spinnaker/include/DeviceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceArrivalEventHandler.h \
		/opt/spinnaker/include/DeviceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceRemovalEventHandler.h \
		/opt/spinnaker/include/DeviceEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceEventHandler.h \
		/opt/spinnaker/include/ImageEventHandler.h \
		/opt/spinnaker/include/Interface/IImageEventHandler.h \
		/opt/spinnaker/include/ImageListEventHandler.h \
		/opt/spinnaker/include/Interface/IImageListEventHandler.h \
		/opt/spinnaker/include/InterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/InterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/SystemEventHandler.h \
		/opt/spinnaker/include/Interface/ISystemEventHandler.h \
		/opt/spinnaker/include/DeviceEventUtility.h \
		/opt/spinnaker/include/ImageUtility.h \
		/opt/spinnaker/include/ImageUtilityCCM.h \
		/opt/spinnaker/include/ImageUtilityHeatmap.h \
		/opt/spinnaker/include/ImageUtilityPolarization.h \
		src/cuda_functions.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dai/Documents/JetsonCamApp/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dai/Documents/JetsonCamApp -I/usr/local/cuda/include -I/opt/spinnaker/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/appwindow.h -o moc/moc_appwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/main.o: src/main.cpp src/appwindow.h \
		src/camerahandler.h \
		/opt/spinnaker/include/Spinnaker.h \
		/opt/spinnaker/include/SpinnakerPlatform.h \
		/opt/spinnaker/include/SpinnakerDefs.h \
		/opt/spinnaker/include/SpinGenApi/GCBase.h \
		/opt/spinnaker/include/SpinGenApi/GCTypes.h \
		/opt/spinnaker/include/SpinGenApi/GCString.h \
		/opt/spinnaker/include/SpinGenApi/GCStringVector.h \
		/opt/spinnaker/include/SpinGenApi/GCUtilities.h \
		/opt/spinnaker/include/SpinGenApi/SpinnakerGenApi.h \
		/opt/spinnaker/include/SpinGenApi/Node.h \
		/opt/spinnaker/include/SpinGenApi/Types.h \
		/opt/spinnaker/include/SpinGenApi/Autovector.h \
		/opt/spinnaker/include/SpinGenApi/Base.h \
		/opt/spinnaker/include/SpinGenApi/Container.h \
		/opt/spinnaker/include/SpinGenApi/ISelector.h \
		/opt/spinnaker/include/SpinGenApi/INode.h \
		/opt/spinnaker/include/SpinGenApi/Reference.h \
		/opt/spinnaker/include/SpinGenApi/NodeMap.h \
		/opt/spinnaker/include/SpinGenApi/INodeMap.h \
		/opt/spinnaker/include/SpinGenApi/IPort.h \
		/opt/spinnaker/include/SpinGenApi/Synch.h \
		/opt/spinnaker/include/SpinGenApi/IDeviceInfo.h \
		/opt/spinnaker/include/SpinGenApi/ValueNode.h \
		/opt/spinnaker/include/SpinGenApi/IValue.h \
		/opt/spinnaker/include/SpinGenApi/EnumNodeT.h \
		/opt/spinnaker/include/SpinGenApi/EnumNode.h \
		/opt/spinnaker/include/SpinGenApi/IEnumeration.h \
		/opt/spinnaker/include/SpinGenApi/IEnumEntry.h \
		/opt/spinnaker/include/SpinGenApi/IEnumerationT.h \
		/opt/spinnaker/include/SpinGenApi/Pointer.h \
		/opt/spinnaker/include/SpinGenApi/ICategory.h \
		/opt/spinnaker/include/SpinGenApi/IInteger.h \
		/opt/spinnaker/include/SpinGenApi/IFloat.h \
		/opt/spinnaker/include/SpinGenApi/IRegister.h \
		/opt/spinnaker/include/SpinGenApi/IBoolean.h \
		/opt/spinnaker/include/SpinGenApi/IPortRecorder.h \
		/opt/spinnaker/include/SpinGenApi/IPortConstruct.h \
		/opt/spinnaker/include/SpinGenApi/IChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/IString.h \
		/opt/spinnaker/include/SpinGenApi/INodeMapDyn.h \
		/opt/spinnaker/include/SpinGenApi/IDestroy.h \
		/opt/spinnaker/include/SpinGenApi/ICommand.h \
		/opt/spinnaker/include/Exception.h \
		/opt/spinnaker/include/SpinGenApi/EnumEntryNode.h \
		/opt/spinnaker/include/SpinGenApi/PortNode.h \
		/opt/spinnaker/include/SpinGenApi/IntegerNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatNode.h \
		/opt/spinnaker/include/SpinGenApi/StringNode.h \
		/opt/spinnaker/include/SpinGenApi/BooleanNode.h \
		/opt/spinnaker/include/SpinGenApi/NodeCallback.h \
		/opt/spinnaker/include/SpinGenApi/EnumClasses.h \
		/opt/spinnaker/include/SpinGenApi/CategoryNode.h \
		/opt/spinnaker/include/SpinGenApi/CommandNode.h \
		/opt/spinnaker/include/SpinGenApi/RegisterNode.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapter.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterDcam.h \
		/opt/spinnaker/include/SpinGenApi/Compatibility.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/ChunkAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/ChunkPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter.h \
		/opt/spinnaker/include/SpinGenApi/EventPort.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGeneric.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapter1394.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterU3V.h \
		/opt/spinnaker/include/SpinGenApi/EventAdapterGEV.h \
		/opt/spinnaker/include/SpinGenApi/IntRegNode.h \
		/opt/spinnaker/include/SpinGenApi/StringRegNode.h \
		/opt/spinnaker/include/SpinGenApi/FloatRegNode.h \
		/opt/spinnaker/include/SpinGenApi/PortWriteList.h \
		/opt/spinnaker/include/SpinGenApi/Persistence.h \
		/opt/spinnaker/include/SpinGenApi/ISelectorDigit.h \
		/opt/spinnaker/include/SpinGenApi/Filestream.h \
		/opt/spinnaker/include/System.h \
		/opt/spinnaker/include/Interface/ISystem.h \
		/opt/spinnaker/include/InterfaceList.h \
		/opt/spinnaker/include/Interface/IInterfaceList.h \
		/opt/spinnaker/include/InterfacePtr.h \
		/opt/spinnaker/include/BasePtr.h \
		/opt/spinnaker/include/Interface.h \
		/opt/spinnaker/include/Interface/IInterface.h \
		/opt/spinnaker/include/CameraList.h \
		/opt/spinnaker/include/Interface/ICameraList.h \
		/opt/spinnaker/include/Camera.h \
		/opt/spinnaker/include/CameraBase.h \
		/opt/spinnaker/include/Interface/ICameraBase.h \
		/opt/spinnaker/include/TransportLayerStream.h \
		/opt/spinnaker/include/TransportLayerDefs.h \
		/opt/spinnaker/include/TransportLayerDevice.h \
		/opt/spinnaker/include/EventHandler.h \
		/opt/spinnaker/include/Interface/IImageList.h \
		/opt/spinnaker/include/Image.h \
		/opt/spinnaker/include/Interface/IImage.h \
		/opt/spinnaker/include/CameraDefs.h \
		/opt/spinnaker/include/ChunkData.h \
		/opt/spinnaker/include/Interface/IChunkData.h \
		/opt/spinnaker/include/ChunkDataInference.h \
		/opt/spinnaker/include/ImagePtr.h \
		/opt/spinnaker/include/CameraPtr.h \
		/opt/spinnaker/include/TransportLayerInterface.h \
		/opt/spinnaker/include/TransportLayerSystem.h \
		/opt/spinnaker/include/LoggingEventHandler.h \
		/opt/spinnaker/include/Interface/ILoggingEventHandler.h \
		/opt/spinnaker/include/LoggingEventDataPtr.h \
		/opt/spinnaker/include/LoggingEventData.h \
		/opt/spinnaker/include/SystemPtr.h \
		/opt/spinnaker/include/ImageProcessor.h \
		/opt/spinnaker/include/Interface/IImageProcessor.h \
		/opt/spinnaker/include/ImageStatistics.h \
		/opt/spinnaker/include/Interface/IImageStatistics.h \
		/opt/spinnaker/include/ImageList.h \
		/opt/spinnaker/include/InterfaceEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceEventHandler.h \
		/opt/spinnaker/include/DeviceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceArrivalEventHandler.h \
		/opt/spinnaker/include/DeviceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceRemovalEventHandler.h \
		/opt/spinnaker/include/DeviceEventHandler.h \
		/opt/spinnaker/include/Interface/IDeviceEventHandler.h \
		/opt/spinnaker/include/ImageEventHandler.h \
		/opt/spinnaker/include/Interface/IImageEventHandler.h \
		/opt/spinnaker/include/ImageListEventHandler.h \
		/opt/spinnaker/include/Interface/IImageListEventHandler.h \
		/opt/spinnaker/include/InterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceArrivalEventHandler.h \
		/opt/spinnaker/include/InterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/Interface/IInterfaceRemovalEventHandler.h \
		/opt/spinnaker/include/SystemEventHandler.h \
		/opt/spinnaker/include/Interface/ISystemEventHandler.h \
		/opt/spinnaker/include/DeviceEventUtility.h \
		/opt/spinnaker/include/ImageUtility.h \
		/opt/spinnaker/include/ImageUtilityCCM.h \
		/opt/spinnaker/include/ImageUtilityHeatmap.h \
		/opt/spinnaker/include/ImageUtilityPolarization.h \
		src/cuda_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/moc_appwindow.o: moc/moc_appwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_appwindow.o moc/moc_appwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

